version: '3.1'
services:
  discovery:
    build:
      context: .
    depends_on: 
      - db
      - wiremock
      - redis
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DB_DSN=postgresql://discovery:discovery@db:5432/discovery
      - QUALITY_ORACLE_URL=https://testnet2-quality.mysterium.network
      - BROKER_URL=nats://testnet2-broker.mysterium.network
      - UNIVERSE_JWT_SECRET=suchsecret
      - REDIS_ADDRESS=redis:6379
  discosidecar:
    build:
      context: .
      dockerfile: sidecar/Dockerfile
    depends_on: 
      - wiremock
      - redis
    environment:
      - QUALITY_ORACLE_URL=https://testnet2-quality.mysterium.network
      - BROKER_URL=nats://testnet2-broker.mysterium.network
      - REDIS_ADDRESS=redis:6379
      - GECKO_URL=http://wiremock:8080
      - COINRANKING_URL=http://wiremock:8080
      - COINRANKING_TOKEN=suchtoken
  db:
    image: postgres:13-alpine
    container_name: discovery_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=discovery
      - POSTGRES_DB=discovery
      - POSTGRES_PASSWORD=discovery
  wiremock:
    image: rodolpheche/wiremock:2.27.2-alpine
    command: --global-response-templating
    ports:
      - "8004:8080"
    volumes:
      - ./e2e/wiremock/mappings:/home/wiremock/mappings
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    