version: '3.1'
services:
  discovery:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DB_HOST=db:6379
      - DB_PASSWORD=
      - QUALITY_ORACLE_URL=https://testnet2-quality.mysterium.network
      - BROKER_URL=nats://testnet2-broker.mysterium.network
  db:
    image: redis
    container_name: 'discovery_db'
    ports:
      - 6379:6379
