version: '3.1'
services:
  discovery:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DB_DSN=postgresql://discovery:discovery@db:5432/discovery
      - QUALITY_ORACLE_URL=https://testnet2-quality.mysterium.network
      - BROKER_URL=nats://testnet2-broker.mysterium.network
  db:
    image: postgres:13-alpine
    container_name: discovery_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=discovery
      - POSTGRES_DB=discovery
      - POSTGRES_PASSWORD=discovery
